#!/usr/bin/env python3
print("__   __ _____________   ___   _ ____   ___ ______ _____ ")
print("\ \ / /(___  /  ___) \ / / | | |  _ \ / _ \\  ___)  ___)")
print(" \ v /    / /| |_   \ v /| |_| | |_) ) |_| |\ \  | |_   ")
print("  > <    / / |  _)   > < |  _  |  _ (|  _  | > > |  _)  ")
print(" / ^ \  / /__| |___ / ^ \| | | | |_) ) | | |/ /__| |___ ")
print("/_/ \_\/_____)_____)_/ \_\_| |_|____/|_| |_/_____)_____)")
print("                                     (c)JAGERCZECH CORP.")
print("                                                        ")
import sqlite3

def read_database(db_filename='jagerdata.db'):
    """Read data from the SQLite database and print the contents."""
    conn = sqlite3.connect(db_filename)
    cur = conn.cursor()
    
    cur.execute('SELECT * FROM data')
    rows = cur.fetchall()
    
    for row in rows:
        print(row)
    
    conn.close()
    print("Data read and printed from the database.")

if __name__ == "__main__":
    read_database()
